channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.5
  - pip
  - Pillow==8.3.1

  - pip:
    - newspaper3k
    - textblob
    - nltk
    - datefinder
    - pickle
    - pandas==1.3.4
    - scikit-learn==1.0.1
    - numpy==1.21.0
    - streamlit
